### PR TITLE
added the download_bio() function

### PR DESCRIPTION
**Pull request by fuchsia80**
download_bio() acts just like download(), yet it takes a BytesIO object as a parameter, therefore allowing you to save the image to memory and perform operations on it rather than saving it to a file.

### CODE REVIEW

**Comment by arrrlo** [comment]
Hi. Thanks for the update. However, could you please make and update of readme file as well, so I can see the real life example of  download_bio() function. Thanks!

**Comment by fuchsia80** [comment]
Alright, I totally forgot about that, haha

**Comment by arrrlo** [comment]
That looks nice now. Thanks!
I will merge your changes.

Also, there are few thing I will change after the merge:
- donwload_bio() should be renamed to get_bytes_io()
- will move myBytesIO into the method
- the method will return bytes io object

**Comment by fuchsia80** [comment]
In my opinion, the name is fine but myBytesIO shouldn't be in the method (if you mean in-example it would make the first myBytesIO.seek(0) obsolete and in the library itself it makes no sense because it's an outer object you'd want to use in your code) and I wasn't sure about returning the BytesIO object via the method because I didn't know its purpose and I thought it could possibly break it, since other modules might expect a path. I'd guess PIL based resize() would be okay with the BytesIO though.

**Comment by arrrlo** [comment]
OK, I got your point regarding the outer object.
But I did some changes. Check out the latest commit.

**Comment by fuchsia80** [comment]
Looks great! I don't see the point of copy_to() though, since it can be done manually without an issue and making an object just for the raw data makes it temporary, which makes it a bit more unpredictable.

**Comment by arrrlo** [comment]
It's because the copy_to() method is now used internally, so why not having it for external use as well. Same goes for the get_raw_data() method. And if you call copy_to() without raw data, it will be fetched automatically. Check the readme file.

Anyway, thanks for making this package better :)

**Comment by fuchsia80** [comment]
Alright, thanks for clearing that up a bit. Glad I could make my first contribution!

**Pull request merged**
